test_that("failing test", {
  stop("A failure in a test", call. = FALSE)
})
